#spring.application.name=user
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/mydb
    username: admin
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000
      pool-name: app-hikari
  jpa:
    hibernate:
      ddl-auto:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
logging:
  level:
    org.hibernate.SQL: debug      # ?? ? SQL ??
